package com.biddan606.timeslot.mock;

import com.biddan606.timeslot.user.domain.User;
import com.biddan606.timeslot.user.service.port.UserRepository;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import org.springframework.util.Assert;

public class FakeUserRepository implements UserRepository {

    private Long autoGeneratedId;
    private final List<User> users;

    public FakeUserRepository() {
        autoGeneratedId = 0L;
        users = new ArrayList<>();
    }

    @Override
    public User save(User user) {
        Assert.notNull(user, "유저는 null 일 수 없습니다.");

        if (isNew(user.getId())) {
            User newUser = User.builder()
                    .id(++autoGeneratedId)
                    .loginId(user.getLoginId().value())
                    .nickname(user.getNickname().value())
                    .password(user.getPassword().value())
                    .build();
            users.add(newUser);

            return newUser;
        }

        boolean removed = users.removeIf(element -> Objects.equals(element.getId(), user.getId()));
        if (!removed) {
            throw new IllegalStateException("이미 유저가 존재하지 않습니다.");
        }
        users.add(user);

        return user;
    }

    public void deleteAll() {
        users.clear();
        autoGeneratedId = 0L;
    }

    private boolean isNew(Long id) {
        return id == null;
    }
}
